[project]
name = "pystk-project-team-leclair"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "omegaconf>=2.3.0",
    "pysupertuxkart2>=0.6.8",
]
