#valeurs a ajuster dans la fonction correction_centrePiste
correction: 0.5

#seuil a ajuster dans la fonction DetecteVirage():

curvature: 0.35

#valeurs a ajuster dans la fonction adapteAcceleration():

acceleration:      
  sans_virage: 0.90   #acceleration avant de rencontrer un virage

virages:
  drift: 2.80   #seuil necessitant un drift (tres serrer)
  serrer:       #intervale viarges serres
    i1: 1.80 
    i2: 2.80 
  moyen:        #intervale viarges moyen
    i1: 0.85 
    i2: 1.80  
  

# pour la fonction reaction_items

angle_evite_p :  0.61
angle_evite_n :  -0.61
